######################### CONFIGURATION FOR LVMEXPBOOT #########################
##                                                                            ##
##   LVM EXPBOOT IS AN UTILITY TO RESIZE LVM PARTITIONS, CALLED MANUALLY OR   ##
##   BY CLOUD-INIT AT BOOT TIME. RATIO / SIZE ARE EXPRESSED IN PERCENT / GB   ##
##                                                                            ##
################################################################################

# Set to 1 to prevent lvmexpboot from actually resizing the partitions
DEBUG=0

# This should be the name of the system volume group
VG_ROOT="vg_root"

# This array should enumerate every logical volume in the root group
# Proper naming according to logical volume path takes place below
# feel free to add/remove according to your system partition scheme
LVS=("SWAP" "USR" "TMP" "VARTMP" "VAR" "LOG" "AUDIT" "OPT" "HOME" "ROOT")

PATH_SWAP="swap"
RATIO_SWAP=6
MAXS_SWAP=8

PATH_USR="usr"
RATIO_USR=24
MAXS_USR=16

PATH_TMP="tmp"
RATIO_TMP=6
MAXS_TMP=8

PATH_VARTMP="var_tmp"
RATIO_VARTMP=6
MAXS_VARTMP=8

PATH_VAR="var"
RATIO_VAR=16
MAXS_VAR=10

PATH_LOG="log"
RATIO_LOG=6
MAXS_LOG=4

PATH_AUDIT="audit"
RATIO_AUDIT=6
MAXS_AUDIT=4

PATH_OPT="opt"
RATIO_OPT=5
MAXS_OPT=12

PATH_HOME="home"
RATIO_HOME=15
MAXS_HOME=32

PATH_ROOT="root"
RATIO_ROOT=10
MAXS_ROOT=16